### ISSUE TITLE
Issue linux with Gulp

### ISSUE THREAD

**Issue by sarahgarcin** [julien-gargot/plainkit#1]
I had this issue on linux when I launch gulp:
https://github.com/gulpjs/gulp/issues/217

You fix this with the command

```echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p```

**Comment by julien-gargot** [comment]
It’s a Arch problem, not gulp. Problem appends with Owncloud or Dropbox as well. 
See: https://bugs.archlinux.org/task/21969 or https://wiki.archlinux.org/index.php/Dropbox#Filesystem_monitoring_problem.
